"use client"
import { Inter } from "next/font/google";
import { useRouter } from 'next/navigation';
import "./globals.css";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Icon } from '@iconify/react';
import Styles from '@/app/layout.module.css';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter()
  const [isProfileMenuOpen, setProfileMenuOpen] = useState(false);
  const toggleProfileMenu = () => {
    setProfileMenuOpen(!isProfileMenuOpen);
  };

  const handleLogout = () => {
    localStorage.removeItem('authToken');
  };

  // useEffect(() => {
  //   const authToken = localStorage.getItem('authToken');
  //   if (!authToken) {
  //     router.push('/auth');
  //   }
  // }, [])

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav className="justify-between relative" style={{ padding: '10px', borderBottom: '1px solid #ccc', display: 'flex' }}>
            <div>
              <Link href="/">
                <span style={{ marginRight: '15px' }}>Home</span>
              </Link>
              <Link href="/customer">
                <span style={{ marginRight: '15px' }}>Customer</span>
              </Link>
              <Link href="/product">
                <span>Product</span>
              </Link>
            </div>
            <span onClick={toggleProfileMenu}>
              <Icon icon="iconamoon:profile-circle-fill" color="#fff" width="32" height="32" />
              {isProfileMenuOpen && (
                <div className={`${Styles.profileMenu} bg-[#4f4e4e] hover:bg-[#545353]`}>
                  <ul>
                    {(
                      <Link href="/auth"><li onClick={handleLogout}>Sign out</li></Link>
                    )}
                  </ul>
                </div>
              )}
            </span>
          </nav>
          <div style={{ padding: '20px' }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
